version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: Saas_postgres
    restart: always
    environment:
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: Senha@123
      - POSTGRES_DB: Saas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data

volumes:
  postgres_data: